background {
monitor = 
path = ~/.config/hypr/wp/wp1.jpg
}

input-field {
    monitor =
    size = 250, 40
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(15, 15, 15)
    inner_color = rgb(22, 22, 22)
    font_color = rgb(200, 10, 10)
    font_family = JetBrains Mono
    fail_color = rgb(204, 92, 92)
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    shadow_passes = 0
    position = 0, -35
    halign = center
    valign = center
}

label {
    monitor =
    text = <i>$ATTEMPTS</i>
    text_align = center
    font_size = 10
    font_family = JetBrains Mono
    position = 10, 0
    halign = left
    valign = top
    color = rgb(222, 222, 222)
}

label {
    monitor =
    text = $LAYOUT[eng, rus]
    text_align = center
    font_size = 15
    font_family = JetBrains Mono
    position = -10, 0
    halign = right
    valign = top
    color = rgb(222, 222, 222)
}

